### ISSUE TITLE
ENH: avoid having to run FreeSurferEnv.sh

### ISSUE THREAD

**Issue by GaelVaroquaux** [nipy/PySurfer#102]
In the different places where pysurfer calls freesurfer commands, the following idiom would enable working without sourcing "FreeSurferEnv.sh" before opening Python:

<pre>
subprocess.call(
      'source $FREESURFER_HOME/FreeSurferEnv.sh; mri_vol2surf --src %s --out %s.left.mgz --srcreg $FREESURFER_HOME/average/mni152.register.dat --hemi lh'
      % (tmp_file.name, outfile), shell=True, executable="/bin/bash")
</pre>

It would be trivial to change the various calls to "subprocess.call" like this, and thus make things more user-friendly.

**Comment by effigies** [comment]
Just noticed this is still open. @GaelVaroquaux did #132 cover your use case?

**Comment by Eric89GXL** [comment]
Closing due to #132, feel free to reopen if this still occurs
