### ISSUE TITLE
Get rid of the config file?

### ISSUE THREAD

**Issue by mwaskom** [nipy/PySurfer#120]
I almost always find the `config_opts` dictionary to be a huge pain. The lack of tab completion in IPython means I always have to hunt to find the right name for the keys, and it's weird to pass an extra dictionary of keyword arguments.

I can't even remember why those options were implemented this way, though I suspect it made reading them from the config file easier. I would like to get rid of the config_opts dictionary and make its entries first-class keyword arguments in `Brain`. (We can keep `config_opts` for a release cycle or two and fire a warning when people use it, to avoid too much disruption).

But more generally, it's worth thinking about just killing the config file itself. I've come to really dislike this approach to customization because it means the scripts/notebooks you write aren't fully reproducible without metadata, and there's no indication in the code that the metadata existed at the time it was executed. (i.e., the script won't even crash, you'll just get a result that looks different).

I also suspect that the config file is relatively underutilized.

Would anyone object to just getting rid of the config file and making everything be specified in the `Brain` constructor?

**Comment by mwaskom** [comment]
Soliciting comment from @Eric89GXL, @agramfort, and anyone else who wants to weigh in on whether they feel the config file is an integral part of their pysurfer workflow and is worth keeping.

**Comment by agramfort** [comment]
+1

and I personally don't use the config file

**Comment by Eric89GXL** [comment]
+1, same here (including the annoyances with working with `config_opts`)

**Comment by mwaskom** [comment]
Closed with #121
