### ISSUE TITLE
offscreen rendering still requires exported display

### ISSUE THREAD

**Issue by gciccarelli3** [nipy/PySurfer#124]
Hi,

I'm running pysurfer on a cluster and pysurfer is still exporting a display "in the background".

I'm running ubuntu 14.04 LTS, 
ssh -XYC into cluster, 
python pysurferscrip.py

and pysurfer launches a VTK/opengle process of somekind on the computer I'm using to ssh.  

---

brain=Brain('fsaverage', hemi_str, 'pial', curv=None,
              config_opts={"cortex": "bone",
                           "background": "white"}, offscreen=True)

**Comment by mwaskom** [comment]
I'm not an expert on that side of things but my understanding is that yes, Mayavi always needs to use a graphics client to draw things, and the offscreen flag just prevents a full GUI window from being launched. For truly "offscreen" rendering I think you'll want to look into using Xvfb, which I think is the best approach for using mayavi on a cluster.

**Comment by lrq3000** [comment]
Maybe this can be of interest to you: [Mayavi Tips and Tricks: Off-screen rendering](http://docs.enthought.com/mayavi/mayavi/tips.html#off-screen-rendering). In particular, you can use a virtual framebuffer.

**Comment by Eric89GXL** [comment]
Yes, check the Mayavi docs for how to deal with this. You can get full software rendering with Mesa if you really want
