### ISSUE TITLE
mri_parse_sdcmdir (equivalent) in pysurfer

### ISSUE THREAD

**Issue by TheChymera** [nipy/PySurfer#127]
Hi guys, I would like to avoid using freesurfer for most of my neuroimaging processing needs. I was hopng PySurfer could help me out in sme cases. Does PySurfer have any equivalent for `mri_parse_sdcmdir`? I need this function to parse some dicom files that I want to convert to nifti.

**Comment by mwaskom** [comment]
Hi, No PySurfer is just for visualization. You could look at Nibabel, I think they have some ability to interact with DICOM files.

**Comment by TheChymera** [comment]
Thank you for the clarification.
