### ISSUE TITLE
Should we do a release?

### ISSUE THREAD

**Issue by mwaskom** [nipy/PySurfer#136]
There has been a handful of new features since 0.5, including some API changes, that would be good to get out the door so people can update code that relies on a released version.

I was hoping to solve https://github.com/nipy/PySurfer/issues/91, but am at a loss for what the issue is.

Any objections to cutting 0.6 soon? @Eric89GXL, @agramfort, others?

**Comment by Eric89GXL** [comment]
Sounds reasonable to me, it would be a good idea to push out a release

**Comment by agramfort** [comment]
+1 for release too. It's long overdue indeed.

**Comment by mwaskom** [comment]
Better late than never
