### ISSUE TITLE
add_data (and elsewhere we accept arrays) should convert input

### ISSUE THREAD

**Issue by mwaskom** [nipy/PySurfer#140]
Been using pandas objects more lately and have been annoyed at having to use `.values` repeatedly, when pysurfer could easily call `np.asarray` on the inputs, I think.

**Comment by Eric89GXL** [comment]
sounds reasonable to me

**Comment by agramfort** [comment]
fine with me too

**Comment by larsoner** [comment]
At least for `add_data` this appears to be implemented:

https://github.com/nipy/PySurfer/blob/master/surfer/viz.py#L1063

Feel free to open a quick PR if others are missing
