### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mwaskom** [nipy/PySurfer#143]
Just wanted to note that it looks like progress is being made in getting Mayavi on Python3: https://github.com/enthought/mayavi/pull/250

We should keep an eye on that and try to get PySurfer working when Mayavi stabilizes.

**Comment by tntdynamight** [comment]
How is the status on this with VTK 7.0.0 and mayavi 4.4.4?

**Comment by agramfort** [comment]
apparently we should be able to make it work now and I can finally switch to python 3 !

any success anyone installing mayavi on py35? no conda package yet apparently.

**Comment by grlee77** [comment]
I was able to install mayavi 4.4.4 and vtk 7 on linux.

There are mayavi 4.4.4 (conda-forge/staged-recipes#285) and VTK 7 (conda-forge/staged-recipes#453) conda recipe in progress (cross-platform for Python 2.7, 3.4, 3.5).  Any feedback there would be welcome.  Python 2 & 3 packages for several of the dependencies (apptools, envisage, traits, pyface, traitsui, etc) have been completed and are available through the conda-forge channel.

**Comment by Eric89GXL** [comment]
I was also able to install on Ubuntu, on it now
