### ISSUE TITLE
surfer library error (gablab neuroimaging)

### ISSUE THREAD

**Issue by centanni** [nipy/PySurfer#144]
Hello all,
I'm getting this error that seems to be part of the surfer library. Any thoughts on how to troubleshoot? Thanks!!

////////////    task001: zstat01    ////////////
Traceback (most recent call last):
  File "l2_screenshots.py", line 91, in <module>
    take_screenshots(tasks ,contrasts, l2_path, model)
  File "l2_screenshots.py", line 17, in take_screenshots
    contrast_lh=project_volume_data(zstat,"lh",subject_id=template,smooth_fwhm=0.3)
  File "/om/project/ran/env/ran_py/lib/python2.7/site-packages/surfer/io.py", line 179, in project_volume_data
    env = dict(line.split('=', 1) for line in envout.split('\n') if line)
ValueError: dictionary update sequence element #73 has length 1; 2 is required
X Error of failed request:  GLXBadContextTag
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  458
  Current serial number in output stream:  458

**Comment by effigies** [comment]
This seems to be a consequence of #132. Can you give the branch in #149 a try?

Sorry about the slow response.
