### ISSUE TITLE
brain is in ms when stc is in seconds

### ISSUE THREAD

**Issue by matt-erhart** [nipy/PySurfer#147]
I'm trying to save a movie of an stc in with tmin etc and times in seconds but when I create a brain object it is converted to ms in ...data_dict['lh']['time']. Is this a bug or is there some conversion I need to do?

**Comment by mwaskom** [comment]
Please provide the exact code you are using. It is hard to say what you need to do if all the information we have is "with tmin etc".

**Comment by mattjerhart** [comment]
Sure thing, let me know if you need to know more.
```python 
   group_avg_stc = sum([i[0] for i in subj_stcs]) / len([i[0] for i in subj_stcs])
    brain = group_avg_stc.plot(subject='fsaverage',hemi='split',
                  subjects_dir=fs_dir,views=['lat', 'med'],
                  config_opts=dict(width=2500, height=1400),
          colormap='jet')
```
group_avg_stc.tmin and tstep are in seconds. group_avg_stc.times is in seconds.
brain.data_dict['lh']['time'] is in ms.

**Comment by christianbrodbeck** [comment]
This inconsistency was recognized, and was solved by introducing the `time_unit` parameter in mne (see [mne docs](http://martinos.org/mne/stable/generated/mne.SourceEstimate.html#mne.SourceEstimate.plot)) so I think this issue can be closed.
