### ISSUE TITLE
make_montage error

### ISSUE THREAD

**Issue by natalieklein** [nipy/PySurfer#150]
Hi all, I get the following error when I try to use make_montage or save_montage.

```
File "/anaconda/lib/python2.7/site-packages/surfer/viz.py", line 73, in make_montage
    import Image
ImportError: No module named Image
```

In ipython, I can do "from PIL import Image" just fine but just "import Image" by itself gives the same error. I tried to look at the link mentioned in the comments just prior to this line in make_montage but it did not illuminate anything for me... Am I missing some library, or is there something else I need to do to make this work?

Thank you!

**Comment by Eric89GXL** [comment]
We should probably do `from PIL import image`. Can you make a PR?
