### ISSUE TITLE
Q: contour from data

### ISSUE THREAD

**Issue by kingjr** [nipy/PySurfer#153]
Hi,

I'm trying to plot the [contour](https://pysurfer.github.io/examples/plot_topographic_contours.html) of [an activation map](https://pysurfer.github.io/examples/plot_meg_inverse_solution.html).

I'm struggling to understand how I can convert my data array whose shape is `n_vertices=20484` (`10242` per hemisphere of fsaverage with `oct=5`) to an overlay array of shape `163842`, (which seems to relate to `brain._geo.curv`?)

Any idea on how to do this?

**Comment by Eric89GXL** [comment]
`stc.morph` with the "None" grade designed to fill the high-density mesh

**Comment by Eric89GXL** [comment]
Oh sorry though this was `MNE`, heh.

Take a look at how STCs would be plotted using PySurfer, it would use the same code. You need to upsample it using smoothing steps. If you can't find it in the docs I'll look.

**Comment by kingjr** [comment]
Nope, I'm getting stuck. I don't know the package well enough :/

Are you saying we can plot activation contours in MNE?

**Comment by Eric89GXL** [comment]
What do you mean by "activation contours"? You mean STCs? Yes `stc.plot()` wraps to PySurfer.

**Comment by Eric89GXL** [comment]
For non-STCs look at the STC example, it upsamples from the decimated mesh to the high-resolution one:

https://github.com/nipy/PySurfer/blob/master/examples/plot_meg_inverse_solution.py#L60

**Comment by kingjr** [comment]
I would like to add a contour overlay on top of activation map similar. The contour would be similar to this, but using a single line:
![plot_topographic_contours](https://cloud.githubusercontent.com/assets/4881164/15942760/d8b02196-2e53-11e6-8c84-cff350e5b77d.png)

This would be to show the effect size (color coded) and surround the significant clusters with a line analogous to this:
![contour](https://cloud.githubusercontent.com/assets/4881164/15942846/446fe330-2e54-11e6-9cc3-e64f04a83b4e.png)

**Comment by Eric89GXL** [comment]
1. Do `stc.morph` in MNE-Python with `grade=None` to fill the high-resolution mesh
2. Find a PySurfer example of contour plots
3. Tweak the properties of the underlying Mayavi object if necessary to get the single contour to be at the right value

**Comment by Eric89GXL** [comment]
(after morph you can use `stc.lh_data` and `stc.rh_data` or similar to get the left and right hemi data, which PySurfer will want)

**Comment by kingjr** [comment]
Works nicely, thanks.
