### ISSUE TITLE
jupyter notebook?

### ISSUE THREAD

**Issue by andrebeu** [nipy/PySurfer#164]
Any suggestions for how to make images with PySurfer on jupyter notebook?

**Comment by mwaskom** [comment]
Are you having a specific problem?

**Comment by F-A** [comment]
@andrebeu What you want is to have PySurfer images in jupyter notebook?
I'm small library to include the PySurfer images as inline for jupyter notebook:

**Comment by larsoner** [comment]
This is dependent upon Mayavi, see:

http://docs.enthought.com/mayavi/mayavi/tips.html#using-mayavi-in-jupyter-notebooks

**Comment by zuxfoucault** [comment]
I installed PySerfer via `conda create -n pysurfer2 -c conda-forge python=3.6 pysurfer`, and did `jupyter nbextension install --py mayavi --user`

Still couldn't make images inline with jupyter notebook...
Any suggestions? Thanks!
