### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by christianbrodbeck** [nipy/PySurfer#165]
Would you consider doing a release @mwaskom ? There are a couple of things here that make plotting MNE-Python source estimates nicer.

**Comment by mwaskom** [comment]
Sure. Can you go through recent PRs and make sure everything is reflected in the CHANGES file? In particularly I think we now support Python 3 even though that isn't advertised (and I think the setup.py classifiers should be updated too, if they weren't in that PR).

**Comment by christianbrodbeck** [comment]
Great!  I made a PR adding the additional changes to the file.
