### ISSUE TITLE
Mac ox 10.11.6 install issue

### ISSUE THREAD

**Issue by anbai106** [nipy/PySurfer#169]
Hellow, 
I installed pysurfer on My mac, but I found it quite trivial, the first time I installed the mayavi with conda, but it degenerated my other packages like pandas, and then run` pip install pysurfer`, so it works but not perfectly, after I update pandas, because I have another project which require higher version of pandas, pysurfer crashed my anaconda(really cranshed everything), so I reinstalled anaconda and reinstall pysurfer, this time I install mayavi with `pip install mayavi`, and then I find my qt version is not 4, but 5, so I degenerated it to be 4, and also, the vtk version of 6.3.0 does not work, i degenerated it to be 5.10.1, so right now I can run the example code from your example gallery, [http://pysurfer.github.io/examples/plot_label.html](url), 
it gaves me warning like this:

> /Users/junhao.wen/anaconda2/lib/python2.7/site-packages/mayavi/tools/camera.py:288: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if focalpoint is not None and not focalpoint == 'auto':

And also, the image does not display, but all with gray color like this:
<img width="800" alt="capture d ecran 2016-12-07 a 21 02 30" src="https://cloud.githubusercontent.com/assets/16743978/20984370/2b798430-bcc0-11e6-8f81-27627bc9bda3.png">

In ipython, if I do `gui qt` first, and i run the code, it will gave me errors like 

> ValueError: API 'QDate' has already been set to version 1

I really like pysurfer, but honestly, it is really difficult to install it on Mac.

the environment variables are included in .zshrc
`export QT_API=pyqt
export ETS_TOOLKIT=qt4`

Can you help me???

**Comment by mb3152** [comment]
I am having this issue as well.

**Comment by mwaskom** [comment]
@mb3152 can you be a bit more specific? The initial issue seems to discuss a few separate issues.

**Comment by mb3152** [comment]
Hey, thanks for responding! I posted a full issue of it here:

https://github.com/nipy/PySurfer/issues/171

**Comment by Eric89GXL** [comment]
These are really `mayavi` packaging issues, see e.g.:

https://github.com/enthought/mayavi/issues/84
https://github.com/ContinuumIO/anaconda-issues/issues/1365
