### ISSUE TITLE
Generate Surface file from asegstats 

### ISSUE THREAD

**Issue by transpersonify** [nipy/PySurfer#170]
Hello,
I have been visualizing the resting state correlations using nifti files till now. However, I have a new functional connectivity data for which I have only these files available:
1. Text files containing  freesurfer aseg stats data for each subject generated through [this](https://surfer.nmr.mgh.harvard.edu/fswiki/asegstats2table) command.
2. Co-ordinates and name for 68 ROIs from Desikan-Killiany atlas.
3. Correlation values between each ROI pairs. 

Is it possible to generate surface representation similar to [this](https://pysurfer.github.io/examples/plot_resting_correlations.html) using this information?

**Comment by mwaskom** [comment]
I think you want to do something like this: http://pysurfer.github.io/examples/plot_parc_values.html

**Comment by transpersonify** [comment]
Yes this is exactly what I wanted to do. Thanks ! Closing the issue.
