### ISSUE TITLE
Conda-forge

### ISSUE THREAD

**Issue by christianbrodbeck** [nipy/PySurfer#174]
After some trial and error I managed a working conda-forge feedstock: https://github.com/conda-forge/staged-recipes/pull/2201. That could simplify installation with dependencies and use of virtual envs with `conda`. If anyone here is interested in being on the maintainer list let me know.

**Comment by Eric89GXL** [comment]
Feel free to add me

**Comment by christianbrodbeck** [comment]
I added you @Eric89GXL

**Comment by christianbrodbeck** [comment]
The feedstock is up at https://github.com/conda-forge/pysurfer-feedstock. After adding the condo-forge channel (`$ conda config --add channels conda-forge`) you can now install with `$ conda install pysurfer`. We did not add `IPython` to the dependencies, I wonder whether we should, since the command line script seems to use IPython.
