### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by transpersonify** [nipy/PySurfer#175]
I am trying to run the example codes and getting the following error after the colormap is displayed:

ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/Rendering/OpenGL/vtkOpenGLTexture.cxx, line 200
vtkOpenGLTexture (0x6d003f0): No scalar values found for texture input!

ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/Rendering/OpenGL/vtkOpenGLTexture.cxx, line 200
vtkOpenGLTexture (0x6d003f0): No scalar values found for texture input!

ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/Rendering/OpenGL/vtkOpenGLTexture.cxx, line 200
vtkOpenGLTexture (0x6d003f0): No scalar values found for texture input!

ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/Rendering/OpenGL/vtkOpenGLTexture.cxx, line 200
vtkOpenGLTexture (0x6d003f0): No scalar values found for texture input!

ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/Rendering/OpenGL/vtkOpenGLTexture.cxx, line 200
vtkOpenGLTexture (0x6d003f0): No scalar values found for texture input!

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
PyAssertionError: C++ assertion "GetEventHandler() == this" failed at ../src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wx._core.PyAssertionError: C++ assertion "GetEventHandler() == this" failed at ../src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

Please help me solve this. Thanks.

**Comment by mwaskom** [comment]
Please be more specific about "the example codes". There are many examples.

**Comment by transpersonify** [comment]
I tried two of them: plot_probabilistic_label.py &  plot_parc_values.py Both of them gave the same error.

**Comment by mwaskom** [comment]
We also need more information about your system, how you are trying to run the scripts, etc. It's very difficult to diagnose a problem without knowing exactly what is causing it.

**Comment by transpersonify** [comment]
I am running it on Ubuntu 16.04:  (Linux Workstation 4.4.0-57-generic #78-Ubuntu SMP)
Python version: 2.7.12
Freesurfer version:  freesurfer-Linux-centos6_x86_64-stable-pub-v5.3.0
Pysurfer version: 0.7 (installed via easy_install also tried with cloning and installing the latest github source.)
Mayavi version: 4.4.3
VTK version:  6.2.0
OpenGL version string: 4.5.0 NVIDIA 364.19
octacore CPUs (Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz + Intel NVIDIA GPU 4GB)

Thanks.

**Comment by transpersonify** [comment]
Anyways, I saved the figures in the script before it crashes! I guess this will do as a temporary workaround. Although any help for future would be helpful.

**Comment by mwaskom** [comment]
I'm confused. Your script successfully plots, is able to save a figure, and then raises an error?

**Comment by transpersonify** [comment]
It successfully plots,  then raises an error and the window shuts down due to the crash. But it saves the figure however.

**Comment by mwaskom** [comment]
It sounds like the crash is happening during the exit of however you're running the script (python? ipython? spyder? you haven't said) and not being raised by PySurfer itself?

**Comment by transpersonify** [comment]
The crash was due to spyder and now is taken care of. Thanks. Closing the issue.
