### ISSUE TITLE
Set paremeters of project_volume_data

### ISSUE THREAD

**Issue by sunshineDrizzle** [nipy/PySurfer#187]
Hi. Recently we're using this function to project volume file into surface space. But we are curious about that whether we should smooth our data before projection. Smooth may cause pattern of raw data different, because volume data has been smoothed in preprocessing pipeline, a new step of smoothing (project volume into surface) may affect data analysis results.
A further question is that how did you set the default value of several parameters, such as projarg and fwhm, etc.
Thanks very much.

**Comment by mwaskom** [comment]
I would say that whether you smooth before or after projection is up to you. Surface-based smoothing has some advantages to volume-based smoothing (it avoids partial voluming or blurring across sulci). But typically one would use this function at the end of a data processing pipeline when you have results that you are ready to plot. Smoothing statistical images will not give the same increase in signal-to-noise as smoothing raw data before statistical estimation.

As for default values — no good answer there. 10 steps of fractional sampling across the cortical surface is a fairly common default practice in Freesurfer, but you could sample more or less densely or just sample the midpoint. The default is to do a small amount of surface smoothing to reduce the presence of discrete voxels on the surface, which I found a little distracting, but choice is mostly about aesthetics. Arguably the default should be 0.

**Comment by sunshineDrizzle** [comment]
Thanks for your answer! It's really helpful!
