### ISSUE TITLE
Problem with add_overlay

### ISSUE THREAD

**Issue by bthirion** [nipy/PySurfer#193]
I have the fiollowing problem: I am displying stat msaps on the surface, and would like to show both positive and negative parts. For certain images --not all of them-- I get an error message from VTK
```
ERROR: In /home/ilan/minonda/conda-bld/work/VTK-6.3.0/Common/Core/vtkLookupTable.cxx, line 144
vtkLookupTable (0xcc23d70): Bad table range: [1e+299, -1e+299]
```
and the negtaive part appears with absolute values. The behavior is not consistant across images and I could not figure out the reson for that. 
For instance, taking data.zip from https://filesender.renater.fr/?s=download&token=84efa671-c7c0-3884-ae0c-f9c41c5c5274
The following script outputs very heterogeneous results (see images):
```
from surfer import Brain
import numpy as np
from nibabel import load
import zipfile
zip_ref = zipfile.ZipFile('data.zip', 'r')
zip_ref.extractall()
zip_ref.close()

tex1 = np.array(load('sample_map_lh.gii').darrays[0].data)
tex2 =  np.array(load('grp_stat_lh.gii').darrays[0].data)

brain = Brain("fsaverage", 'lh', "inflated",  title='', views=['lat'])
brain.add_overlay(tex1, hemi='lh', min=3., max=8.)
brain.save_montage('sample_map_lh.png')
# this one is fine with both positive and negative value

brain = Brain("fsaverage", 'lh', "inflated",  title='', views=['lat'])
brain.add_overlay(tex2, hemi='lh', min=3., max=8.)
brain.save_montage('grp_stat_lh.png')
# this one is wrong, only positive
```
![sample_map_lh](https://user-images.githubusercontent.com/234454/27179970-617298aa-51d1-11e7-92a7-92541ef1bbc3.png)
![grp_stat_lh](https://user-images.githubusercontent.com/234454/27179971-61732900-51d1-11e7-9637-50159370622b.png)

Can anybody reproduce / give advice ?

**Comment by mwaskom** [comment]
I can reproduce. Not sure yet what's going on.

**Comment by bthirion** [comment]
Oops. I'll have to revise my scripts. Thx for checking !
