### ISSUE TITLE
Feature request: obtain vertex number by clicking on the brain

### ISSUE THREAD

**Issue by wmvanvliet** [nipy/PySurfer#218]
I really wish I had the ability to click on the brain and get the vertex number and the corresponding index of the data matrix. Sometimes I see something interesting on the cortex and would like to quickly get to the corresponding row in the data matrix.

**Comment by mwaskom** [comment]
This is already built into mayavi. I'm pretty sure you just need to click and then press "p".

**Comment by mwaskom** [comment]
Here's a very simple function that will let you add a mayavi callback to do this:

```python
from mayavi import mlab
from surfer import Brain
b = Brain("fsaverage", "lh", "inflated")
f = mlab.figure("fsaverage")
f.on_mouse_pick(lambda p: print(p.point_id), button="Right")
```

After executing this, right-clicking on a vertex should result in its index being printed to stdout. I'm not sure if there's a simpler way to get the figure handle. It's buried in a private attribute in the `Brain` object (in the `b._figures` nested list), so going through `mlab` to get it seemed to make sense.

**Comment by mwaskom** [comment]
Closing as I don't see a need for any more functionality in pysurfer itself but others can comment/reopen if they want to add something.

**Comment by wmvanvliet** [comment]
I never knew! Thanks for the tips!
