### ISSUE TITLE
Embedded screenshots in docs are very large

### ISSUE THREAD

**Issue by mwaskom** [nipy/PySurfer#225]
Was just looking at the docs and the screenshots now take up considerable more space than I remember.

For example: https://pysurfer.github.io/auto_examples/plot_fmri_activation.html

Here's how it looks to me with my Chrome set to 100% zoom:

<img width="953" alt="screenshot 2018-02-03 15 08 15" src="https://user-images.githubusercontent.com/315810/35771016-1d62bd90-08f4-11e8-9c74-8577478e0ef2.png">

Doesn't seem limited to that example.

Did this change when the docs moved to sphinx-gallery? Can the size of the embedded image be controlled (as I assume it used to be?) Having the figures spill over into the sidebar looks messy.

**Comment by larsoner** [comment]
Yes this would have happened when going to sphinx-gallery.

I don't think there is a way to control the size in SG, as its output matches the one you would get running the script, in this case a 800x800 image.

Once https://github.com/sphinx-gallery/sphinx-gallery/pull/210 lands in SG we can fix this with `max-width: 100%` in the CSS.
