### ISSUE TITLE
Incorrect statements on install page

### ISSUE THREAD

**Issue by mwaskom** [nipy/PySurfer#246]
Just noticed that http://pysurfer.github.io/install.html claims:

> PySurfer requires Python 2.7, and it does not work on Python 3.

But that is no longer true!

Also the page starts by saying:

> Installing PySurfer is quite simple with pip:

But I think that while installing the pysurfer library is simple, in practice that claim is a bit misleading :)

**Comment by dgutman** [comment]
I saw the same flag re: python 2.7--  I am hoping to run this in a docker container I already have setup, but that defaults to 3.6;  is there any functionality that I may expect to not work if I am using python 3+?

**Comment by mwaskom** [comment]
It should work. PySurfer is tested on Python 3.6: https://github.com/nipy/PySurfer/blob/master/.travis.yml

We just forgot to update all the places that information is documented.
