### ISSUE TITLE
add name to display

### ISSUE THREAD

**Issue by EhsanTadayon** [nipy/PySurfer#249]
Hi, 

I'm using add_foci to display several points on the brain surface. Is there any way to show text for each foci as well? I appreciate your help

best
Ehsan.

**Comment by mwaskom** [comment]
I don't think any PySurfer functions will do it but you can add text to figures using mayavi directly with [`mlab.text3d`](http://docs.enthought.com/mayavi/mayavi/auto/mlab_other_functions.html#text3d).
