### ISSUE TITLE
vtk error

### ISSUE THREAD

**Issue by EhsanTadayon** [nipy/PySurfer#255]
Hi, 

I followed the instructions in mne to install both mne and pysurfer ( python 3). I had to manually install mayavi and pysurfer as they failed to install using `conda env create -f environment.yml`. The pysurfer now works in jupyter notebook and it generates the output but it gives me the following warning:

**Warning:**
Exception occurred in traits notification handler for object: vtkCocoaRenderWindow (0x7fdf23ef7800)
  Debug: Off
  Modified Time: 1428174
  Reference Count: 3
  Registered Events: 
    Registered Observers:
      vtkObserver (0x7fdf22c6a690)
        Event: 33
        EventName: ModifiedEvent
        Command: 0x7fdf29478770
        Priority: 0
        Tag: 2
      vtkObserver (0x7fdf29474a60)
        Event: 50
        EventName: CursorChangedEvent
        Command: 0x7fdf29466930
        Priority: 0
        Tag: 1
  Erase: On
  Window Name: Visualization Toolkit - Cocoa
  Position: (0, 0)
  Size: (1600, 1600)
  Mapped: 1
  OffScreenRendering: 0
  Double Buffered: 1
  DPI: 72
  TileScale: (1, 1)
  TileViewport: (0, 0, 1, 1)
  Borders: On
  IsPicking: Off
  Double Buffer: On
  Full Screen: Off
  Renderers:
    Debug: Off
    Modified Time: 1337352
    Reference Count: 1
    Registered Events: (none)
    Number Of Items: 1
  Stereo Capable Window Requested: No
  Stereo Render: Off
  Point Smoothing: Off
  Line Smoothing: Off
  Polygon Smoothing: Off
  Anti Aliased Frames: 0
  Abort Render: 0
  Current Cursor: 0
  Desired Update Rate: 0.0001
  Focal Depth Frames: 0
  In Abort Check: 0
  NeverRendered: 0
  Interactor: 0x7fdf2956b050
  Motion Blur Frames: 0
  Swap Buffers: On
  Stereo Type: RedBlue
  Number of Layers: 1
  AccumulationBuffer Size 0
  AlphaBitPlanes: On
  UseSRGBColorSpace: Off
  AnaglyphColorSaturation: 0.65
  AnaglyphColorMask: 4 , 3
  MultiSamples: 0
  StencilCapable: False
  DefaultFrameBufferId: 0
  MultiSamples: 0
  CocoaManager: 0x7fdf2a309210
  RootWindow (NSWindow): 0x0
  WindowId (NSView): 0x7fdf24d7b220
  ParentId: 0x0
  ContextId: 0x7fdf2a220dc0
  PixelFormat: 0x7fdf2a221ef0
  WindowCreated: No
  ViewCreated: No
  WantsBestResolution: Yes

, trait: aa_frames, old value: 8, new value: 0
Traceback (most recent call last):
  File "/Users/stadayon/anaconda2/envs/mne/lib/python3.6/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/stadayon/anaconda2/envs/mne/lib/python3.6/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/render_window.py", line 217, in _aa_frames_changed
    self._do_change(self._vtk_obj.SetAAFrames,
AttributeError: 'vtkRenderingOpenGL2Python.vtkCocoaRenderWindow' object has no attribute 'SetAAFrames'

**Comment by larsoner** [comment]
This is a Mayavi bug, can you open an issue there?
