### ISSUE TITLE
Question: Displaying Subcortical structures & Cerebellum in PySurfer?

### ISSUE THREAD

**Issue by jnecus** [nipy/PySurfer#257]
Dear team,

I'm struggling to determine whether it is possible to display subcortical structures and cerebellum (i.e the parcellations included in the aparc+aseg.mgz freesurfer file.

PySurfer does an excellent job at plotting individual cortical rois from this file. However, it does not plot the following ROIs which are contained within this file:

Accumbens-area            
Amygdala                  
Caudate                   
Cerebellum-Cortex         
Cerebellum-White-Matter   
Cerebral-White-Matter   
Hippocampus           
Pallidum                  
Putamen            
Thalamus-Proper         

If PySurfer is not built for this then can perhaps point me in the direction of something that will (I've looked at Nilearn but this doesn't seem capable either) .

**Comment by mwaskom** [comment]
How are you hoping to visualize them? PySurfer works with surfaces (hence the name). It could be possible to tessellate the volume masks for the various subcortical ROIs and then plot them in mayavi, possibly in conjunction with a PySurfer cortex mesh, but it's not really something we directly support.

**Comment by mwaskom** [comment]
Also to clarify:

> PySurfer does an excellent job at plotting individual cortical rois from this file. However, it does not plot the following ROIs which are contained within this file.

PySurfer is not actually using that file. It's using the ?h.aparc.annot parcellation, which is defined on the surface. As part of recon-all, those ROIs get mapped into the volume, but it's the volumetric representation isn't used by PySurfer.

**Comment by larsoner** [comment]
Sounds like the question has been answered so I'll close
