### ISSUE TITLE
Cannot display with hemi="split"

### ISSUE THREAD

**Issue by ZaixuCui** [nipy/PySurfer#262]
Hi All,

I am trying to use Pysurfer to display results. However, it display well using hemi="lh" or "rh". However, with hemi="split", it display nothing. Also, with views=['lat','med'], it display nothing. I will be really appreciated if anyone has some suggestions?

When I input comand "from surfer import Brain", it displayed "Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.". 
Not sure if this is the reason?

Thank you so much.

Best
-
Zaixu

**Comment by danjgale** [comment]
I'm also getting this exact same error (with version 0.9.0)

**Comment by danjgale** [comment]
Alright, I was able to figure out a fix on MacOS, which I'll post here:

1) Make sure you have `pyqt5>=5.12` installed (which is the most recent as of the time of this writing. I'm guessing `>=5.10.2` would be sufficient based on [what's mentioned here](https://github.com/enthought/mayavi/issues/595#issuecomment-386097374))

2) Set up the following environment variables ([source](https://github.com/enthought/mayavi/issues/595#issuecomment-366722607)):

```
export ETS_TOOLKIT=qt4
export QT_API=pyqt5
```

From here I was able to enter an ipython session as normal (running `%gui qt`) and run `brain = Brain('fsaverage', 'split', 'inflated', views=['lat', 'med'])` successfully. For reference this works with the following versions:
```
pysurfer                  0.9.0
mayavi                    4.6.2
vtk                       8.1.2
PyQt5                     5.12
pyqt                      5.9.2
```

**Comment by larsoner** [comment]
Thanks @danjgale, closing as this is a mayavi/PyQt5 bug

**Comment by mwaskom** [comment]
Is it correct that the solution is to define `qt4` for one variable and `pyqt5` for another? That doesn't seem right...

**Comment by danjgale** [comment]
@mwaskom I wondered that too... It does seem to do the trick, however. I took it from here: https://github.com/enthought/mayavi/issues/595#issue-293719209

**Comment by mwaskom** [comment]
Fascinating....
