### ISSUE TITLE
The surfer are  always transparent and can see activity in back area from the front sight

### ISSUE THREAD

**Issue by mylee5661** [nipy/PySurfer#263]
Hello, when I used PySurfer to make some picture of my little project,  I find it always be opacity when new surfer are overlaid, so that I  can see some area like supplementary motor area or Precuneus from front view. that will cause confuse like some area in the front  have activated. I have tried many ways but It just doesn't work, here is the codes I used to add the brain and activated map
(brain = Brain("fsaverage", "lh", "inflated", title=None, cortex='classic', alpha=1, size=800, background='white', foreground=None, figure=None, subjects_dir=None, views=['lat'], offset=False, show_toolbar=True, offscreen='auto', interaction= 'terrain', units='mm')
brain.add_overlay(mastat, 0.05, 30, name="mask")
brain.overlays["mask"].pos_bar.lut_mode = "summer"
brain.overlays["mask"].pos_bar.visible = False
![image](https://user-images.githubusercontent.com/46165294/50633704-41c5e280-0f87-11e9-8fae-3e592123d784.png)
you can see the upper yellow area indeed is the SMA area, but it just looks like in precentral area if I place the picture central in the screen, so how can I make the brain surface opaque ? 
Thanks very much

**Comment by mwaskom** [comment]
I think this is the same issue as https://github.com/nipy/PySurfer/issues/258

**Comment by mylee5661** [comment]
> I think this is the same issue as #258

wow, that just solve my problem
thank you very much

**Comment by mwaskom** [comment]
Sure thing!

**Comment by athiede13** [comment]
I have had this visualization problem on Linux for a long time now and this fix works! Thank you so much
