### ISSUE TITLE
Transparent rending with noisy particles

### ISSUE THREAD

**Issue by solleo** [nipy/PySurfer#266]
Hi all,

I tried to visualize an inverse solution using a default option:
```
brain = stc.plot(subject=subj, surface='inflated', hemi='rh', time_viewer=False, initial_time=time_max)
```

and got this kind of image:
![all_tsss_hp0 5Hz_notch50sHz_cor_ave-rh stc](https://user-images.githubusercontent.com/1589217/56475930-10512400-645d-11e9-8790-1ac3938003b4.png)

I've tried various options and noticed that with Transparent=True the binarized curvature mapping is rendered in front of the dSPM map. With Transparent=False the dSPM map was correctly rendered (without black dots/edges sticking out).

I'm using NVIDIA Quadro P400 (driver v415.27) on Ubuntu 16.04.6 LTS.

I just wonder if anyone has experienced a similar thing before?

**Comment by mwaskom** [comment]
Sounds like https://github.com/nipy/PySurfer/issues/258

**Comment by solleo** [comment]
Thanks! It wasn't really the same issue as in #258: backface_culling didn't fix it. But this solved the problem by adjusting force_opaque = True

![snapshot](https://user-images.githubusercontent.com/1589217/56504481-9cf3f480-64e6-11e9-9c98-00e23ea87f85.png)

Now, I know this is not really a PySurfer question, but could someone please point where I should read to know how to scriptize this? I think there should be some way to access the surface object handle, but I'm not familiar with mayavi.... 

+ Oh well, after some time, I found that <_f> attributes have handles of scenes, and mayavi script generator also gave me a hint, so I finally figured out how to do this:
```
idx_brain = 0
brain.brain_matrix[idx_brain][0]._f.children[1].children[0].children[0].children[0].actor.actor.force_opaque = True
```
This solves my issue, so I'm closing it.
