### ISSUE TITLE
add_overlay colors the whole brain when given all zeros

### ISSUE THREAD

**Issue by alexrockhill** [nipy/PySurfer#267]
I'm not sure if this is the intended behavior but it was quite confusing to me why the whole brain was colored. 

Minimally reproducible example:

brain = Brain('fsaverage', 'lh', 'inflated', subjects_dir=fs_dir)
brain.add_overlay(np.zeros((1000000)), min=0.04, max=2.5, sign="pos")

**Comment by larsoner** [comment]
`add_overlay` seems to have far fewer capabilities than `add_data`, which is probably what you want to use. Maybe we should make a note saying that `add_data` should be preferred nowadays, unless there is something `add_overlay` does that `add_data` does not.
