### ISSUE TITLE
save_montage on OSX: hemisphere truncated when saving montage

### ISSUE THREAD

**Issue by mattvan83** [nipy/PySurfer#283]
Dear PySurfers,

I used pysurfer 0.10.dev0 on OSX computer and tried to save a dorsal view of both hemispheres using the following self contained example code:
```
b = Brain("fsaverage", "both", "white", cortex=None, background="black")
b.show_view("dor")
n = 163842
for hemi in ["lh", "rh"]:
    for colormap in ["Reds", "Blues"]:
        data = np.random.randn(n)
        b.add_data(data, min=0, max=1, thresh=0, colormap=colormap, colorbar=False, hemi=hemi)
```
This code gave me the correct following dorsal view:
<img width="790" alt="Capture d’écran 2020-01-20 à 20 16 10" src="https://user-images.githubusercontent.com/4630825/72752439-7de3d980-3bc2-11ea-89e9-bdd3a059684f.png">

However, whenever trying to save this view with the following code, one of the hemisphere is truncated in the image saved:
`b.save_montage(os.path.join(WD,"self.contained.example.png"), order=['dorsal'], orientation='v', border_size=15, colorbar=None, row=-1, col=-1)`

![self contained example](https://user-images.githubusercontent.com/4630825/72752533-be435780-3bc2-11ea-9852-f6ec234f67fe.png)

Anyone would have an idea of this problem?

**Comment by mwaskom** [comment]
Is this a distinct issue from #282?

**Comment by mattvan83** [comment]
Not distinct but specific to OSX since the problème didn't appear on CentOS.

Moreover, #282 has been redirected to problem of overlap and conjunction maps, but the truncated view problem is different from these.

**Comment by mwaskom** [comment]
I'm going to close this and we can continue the discussion of the montage truncation on #282. It's very confusing to have multiple issues open describing the same problem.
