### ISSUE TITLE
Problem with overlay rendering when visualizing the inverse problem

### ISSUE THREAD

**Issue by filip-halemba** [nipy/PySurfer#284]
During visualization of inverse problem with mne-python I produced "leaky" picture like in picture below.

![Screenshot from 2020-01-19 22-19-31](https://user-images.githubusercontent.com/7030508/73787780-3e111a80-479c-11ea-92fe-433f9040e49f.png)

I started to asking question on [gitter](https://gitter.im/mne-tools/mne-python) where @larsoner put some advice for me. After few days I resolved my problem by enabling `backface culling` for the overlay.

![Screenshot from 2020-02-03 22-34-32](https://user-images.githubusercontent.com/7030508/73788366-300fc980-479d-11ea-87ba-a67531c5b938.png)
![Screenshot from 2020-02-03 22-34-39](https://user-images.githubusercontent.com/7030508/73788377-369e4100-479d-11ea-89ec-2bb2dac26511.png)

This task was created at the request of @larsoner - https://gitter.im/mne-tools/mne-python?at=5e3899b1e8a838355913a83a

**Comment by wmvanvliet** [comment]
Is there any downside to enabling backface culling by default?

**Comment by larsoner** [comment]
I thought that there were some cases when the brain was partially transparent where it seemed better to have it off. So one option is to enable backface culling when the brain alpha is 1. and disable it otherwise. @wmvanvliet since you can replicate do you want to try?

**Comment by wmvanvliet** [comment]
I've dome some digging around. Unfortunately, the problem goes deeper than backface culling. There is a bug in Qt5 regarding obtaining an OpenGL rendering context with a depth buffer. Somehow, for some non-nvidia chipsets, Qt5 creates a context without depth buffering. Hence vertices are rendered in the wrong order. Hence bad rendering bugs like we see in this issue. Here is a clue: 

http://vtk.1045678.n5.nabble.com/VTK-master-Qt-5-and-Intel-i915-driver-on-Ubuntu-Linux-tt5727112.html

Temporary fix is to switch Mayavi over to the `wx` rendering engine. But that has problems of its own.

**Comment by wmvanvliet** [comment]
Backface culling removes a lot of vertices from the render cue and hence alleviates the problems a bit.

**Comment by larsoner** [comment]
The only other idea I have is trying to tweak the OpenGL rendering to set the [polygon offset (negative values for the ones we want on top) and enabling polygon offset for fill mode](https://www.opengl.org/archives/resources/faq/technical/polygonoffset.htm). Not sure if this requires a functional depth buffer but it might.

**Comment by wmvanvliet** [comment]
Here's how things look with a non-nvidia card. It's not limited to just the overlay:

![fig](https://user-images.githubusercontent.com/428273/74248934-4a3b3180-4ce0-11ea-8bf2-27dcd117cfac.gif)

**Comment by larsoner** [comment]
No offset fill is going to save you from that :(

If a usable workaround is actually to use a `QVTKWidget2` instead of `QVTKWidget`, then we could try updating `mayavi` to use this newer widget. We could also see if `PyVista` could make a corresponding change. There have been depth problems in `mne coreg` that would might also be fixed by such a change.

**Comment by wmvanvliet** [comment]
Way ahead of you :) Mayavi, well pyface, doesn't use `QVTKWidget` directly, but does it's own thing on top of `QGLWidget`: https://github.com/enthought/mayavi/blob/master/tvtk/pyface/ui/qt4/QVTKRenderWindowInteractor.py

**Comment by larsoner** [comment]
Cross-ref to https://github.com/pyvista/pyvista/issues/473. Maybe the fix there combined with using VTK 8.2+ would fix things.

**Comment by larsoner** [comment]
(on my VTK 8.1.2 and NVIDIA hardware my `QVTKRWIBase` is `'QWidget'`)

**Comment by wmvanvliet** [comment]
It would be awesome if we could solve this!

**Comment by larsoner** [comment]
@wmvanvliet you can try conda-forge to see if the 8.2 they have up there can be used:

https://anaconda.org/conda-forge/vtk/files

It might automatically work, and if not, maybe look into what they did in pyvista/pyvista#473 to fix things...
