### ISSUE TITLE
ImportError: Could not import backend for traitsui.  Make sure you         have a suitable UI toolkit like PyQt/PySide or wxPython         installed.

### ISSUE THREAD

**Issue by KangChou** [nipy/PySurfer#302]
`ImportError: Could not import backend for traitsui.  Make sure you
        have a suitable UI toolkit like PyQt/PySide or wxPython
        installed.`

**Comment by KangChou** [comment]
The problem has been solved.
The main reason is the conflict between different versions of QT

**Comment by HusBunia** [comment]
> The problem has been solved. The main reason is the conflict between different versions of QT

Hi, I have met the same problem, could you tell me your Qt version?
