### ISSUE TITLE
Change in import Sequence on Python 3.10 

### ISSUE THREAD

**Issue by ezemikulan** [nipy/PySurfer#316]
Hi, I've just created a new environment with Python 3.10 and noticed that I was unable to use Pysurfer as Brain() couldn't be imported. The problem was with the line:

`from collections import Sequence # (utils.py - line 1)
`

I found that to work in python 3.10 it should be changed to:

`from collections.abc import Sequence
`

I'm not sure how to make the change without breaking backwards compatibility so I'm not submitting a pull request. 

Hope this helps.

**Comment by raphaelchristin** [comment]
I still run into the same error as of Jan 30, 2023. It seems that the proposed pull request was closed without being merged for some reason. I am happy to submit another one but I am curious as to why the previous one was not merged.

**Comment by raphaelchristin** [comment]
Seeing as the last commit was more than a year ago, I am unsure how much time it will take to get something merged.

**Comment by agramfort** [comment]
I am sorry PySurfer is not actively maintained anymore. Would you be
interested in maintaining it?

**Comment by raphaelchristin** [comment]
I am unsure if I have the time to maintain the full package. I would be interested in fixing the compatibility issues introduced by python 3.10 and numpy 1.24.0 but beyond that I unfortunately wouldn't be able to do much. Would that be possible/helpful?

**Comment by agramfort** [comment]
@raphaelchristin I have no time for this anymore. If you make PRs I can merge them. Feel free to adjust the CIs script if need be on the way.
