### ISSUE TITLE
ENH: Python 3 compatibility and changing backend

### ISSUE THREAD

**Issue by Eric89GXL** [nipy/PySurfer#77]
Over at `mne-python` we're looking into migrating to Python3, and one of our biggest roadblocks will be PySurfer / Mayavi. @agramfort has mentioned that Mayavi may not ever be migrated to 3.0, so it might be worth switching to a different backend. I also had to do some pretty ugly hacks to get TraitsUI to support visualization scripting, since it's not built to do that (it is not supported by the devs).

I'm up for looking into the various other backend options here if people are open to the idea of switching backends for `0.5`. Having done a little bit of low-level OpenGL work recently, I think it *might* be possible to go to a backend that only gives us low-level OpenGL calls (as opposed to high-level abstraction like VTK/Mayavi) without too much hassle.

What do people think?

Here are a list of potential ones (I'll update as people suggest or I find them):

- pyqtgraph (MIT)
    - Abstractions for 3D surface plotting
    - Built-in mouse / keyboard interaction
    - Has widgets (GUI-like functionality possible)
    - Requires QT4 / PySide (Mayavi more or less did, too)
- vispy (BSD)
    - Fairly low-level access to OpenGL
- ~~VTK~~ no 3.0 date yet
- ~~XTK~~ most programming in JavaScript, Web interface makes local file usage problematic
- ~~pyopengl / glumpy / pyglet / pygame~~ raw OpenGL only as last resort
- ~~VPython~~ a distribution more than a package
- ~~visvis (BSD)~~ probably not complete enough `mesh` rendering options

**Comment by mwaskom** [comment]
Just wanted to poke at this issue and say that I've recently been playing around a lot with more "interactive" uses of PySurfer, e.g. https://github.com/mwaskom/connexplore. Will vispy allow this kind of mouse-based interaction?

**Comment by Eric89GXL** [comment]
I haven't tried that bit of code, but I can say that you can define any type of mapping between mouse movements / clicks / etc. you want and visual operations (resizing, panning, etc.) by defining different camera classes. `vispy` has a few reasonable defaults built in already that you can choose from, too.

**Comment by mwaskom** [comment]
Cool, good to know that they'll have some interactivity. I think the ability to click on the brain mesh and get a reference to where you clicked is important to a lot of functionality currently absent in pysurfer (but easy to build on top of).

**Comment by Eric89GXL** [comment]
Closing this as a dup of #106 (even though that one came later the discussion is more extensive)
