### ISSUE TITLE
Brain.close() does not free all of its memory

### ISSUE THREAD

**Issue by mwaskom** [nipy/PySurfer#91]
See #88 and #90

**Comment by mwaskom** [comment]
Does anyone have insight into whether we could be doing more here to manage memory? (Or, alternatively, does mayavi just have unavoidable memory leaks?) I've been doing a lot of scripting/interactive stuff recently that has been maxing out memory on my machine, with the only solution being an IPython kernel restart. In notebooks that depend on a fair amount of processing to get the data that will go on the brain, those restarts can be quite annoying.

**Comment by Eric89GXL** [comment]
IIRC we have some circular references somewhere -- we should change one of them to use weakref and it might help.

**Comment by Eric89GXL** [comment]
Can you make some minimal script that blows up memory quickly? That would
make it easier to dig into the issue to see if it's our fault.

**Comment by mwaskom** [comment]
OK, so I have learned some things!

Using [`memory_profiler`](https://pypi.python.org/pypi/memory_profiler) (which is awesome!) with the following script:

import sys
import argparse
import numpy as np
from surfer import Brain

from memory_profiler import memory_usage

```python
def plot():

    p = argparse.ArgumentParser()
    p.add_argument("-iter", default=50, type=int)
    p.add_argument("-close", action="store_true")
    p.add_argument("-screenshot", action="store_true")
    p.add_argument("-out")
    args = p.parse_args(sys.argv[1:])

    if not args.close:
        b = Brain("fsaverage", "lh", "pial")

    usage = np.empty(args.iter)

    for i in xrange(args.iter):

        if args.close:
            b = Brain("fsaverage", "lh", "pial")

        data = np.random.randn(163842)
        b.add_data(data, remove_existing=True)

        if args.screenshot:
            _ = b.screenshot()

        if args.close:
            b.close()

        usage[i] = np.max(memory_usage(-1))

    np.savetxt(args.out, usage)


if __name__ == "__main__":
    plot()
```

invoked like so:

```
python pysurfer_mem.py -out plot.txt
python pysurfer_mem.py -close -out plot_close.txt
python pysurfer_mem.py -screenshot -out shot.txt
python pysurfer_mem.py -screenshot -close -out shot_close.txt
```

and then plotted:

![pysurfer_memory_usage](https://cloud.githubusercontent.com/assets/315810/6604662/246bb566-c7e7-11e4-8460-a674857af9ef.png)

Some takeaways:

- The *major* accrual of memory happens when using `Brain.screenshot`. Unfortunately, that's exactly what you'd be doing in most cases where you're looping over a lot of plots.
- Using `Brain.close` has almost no effect on memory usage
- Memory usage still accrues when not taking screenshots, but not enough to worry deeply about for non-screenshot cases like interactive apps.

So does it make sense to anyone why using `Brain.screenshot` seems to keep so much memory hanging around? Note that I'm not storing the resulting screenshot arrays anywhere (and, anyway, they're only 800 x 800 x 3), which seems unlikely to account for the total memory usage on that plot.

**Comment by Eric89GXL** [comment]
The screenshot call should be pretty simple, my guess is that it's a Mayavi/VTK issue :( You could show it by making some simple scene using a brain triangular mesh and taking a bunch of screenshots.

**Comment by mwaskom** [comment]
Interestingly, it doesn't seem to be the *act* of taking a screenshot:

```python
import sys
import argparse
import numpy as np
from surfer import Brain

from memory_profiler import memory_usage

def plot():

    p = argparse.ArgumentParser()
    p.add_argument("-iter", default=50, type=int)
    p.add_argument("-out")
    args = p.parse_args(sys.argv[1:])

    b = Brain("fsaverage", "lh", "pial")
    data = np.random.randn(163842)
    b.add_data(data, remove_existing=True)

    usage = np.empty(args.iter)

    for i in xrange(args.iter):

        _ = b.screenshot()
        usage[i] = np.max(memory_usage(-1))

    np.savetxt(args.out, usage)


if __name__ == "__main__":
    plot()
```

![screenshot_memory_usage](https://cloud.githubusercontent.com/assets/315810/6605524/da5b7414-c7ed-11e4-97e7-3a299c96529d.png)

**Comment by Eric89GXL** [comment]
I'm going to close this as WONTFIX, since I think it's probably a Mayavi issue
